version: "3"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: sumi
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis
    restart: always
  sumi:
    image: vgwidt/sumi
    restart: always
    env_file:
      - ./.env
    ports:
      - "9080:9080"
    command: sh -c "diesel migration run --config-file ./backend/diesel.toml && ./sumi"
    depends_on:
      - postgres
      - redis
